import "pkg:/source/Format.bs"

namespace Array

    '---------------------------------------------------------------------------
    ' Array.GetCount
    '---------------------------------------------------------------------------
    function GetCount(values as dynamic) as integer

        if values = invalid then return 0

        valueType = Type(values)
        if valueType <> "roArray" and valueType <> "roAssociativeArray" then return 0

        return values.Count()

    end function

    '---------------------------------------------------------------------------
    ' StringArray_ToCommaSeparatedList
    '---------------------------------------------------------------------------
    function JoinStringValues(values as dynamic) as string

        if values = invalid then return ""

        result = ""
        for each value in values
            if result <> "" then result = result + ", "
            result = result + Format.SafeString(value, "")
        end for

        return result

    end function

end namespace
