namespace Number

    '---------------------------------------------------------------------------
    ' Number.ToFloat
    '---------------------------------------------------------------------------
    function ToFloat(value as dynamic, fallback = 0.0 as float) as float
        if value = invalid then return fallback
        return val(value.ToStr())
    end function

    '---------------------------------------------------------------------------
    ' Number.ToInteger
    '---------------------------------------------------------------------------
    function ToInteger(value as dynamic, fallback = 0 as integer) as integer
        if value = invalid then return fallback
        return int(val(value.ToStr()))
    end function

end namespace
